model_path = {
    "GPT-4o": "gpt-4o-2024-11-20",
    "Gemini-1.5-Flash": "gemini-1.5-flash",
    "Claude-3.5-Sonnet": "claude-3-5-sonnet-latest",
    "TinyLLaVA": "tinyllava/TinyLLaVA-Phi-2-SigLIP-3.1B",
    "InternVL2-2B": "OpenGVLab/InternVL2-2B",
    "InternVL2-4B": "OpenGVLab/InternVL2-4B",
    "InternVL2-8B": "OpenGVLab/InternVL2-8B",
    "InternVL2-26b": "OpenGVLab/InternVL2-26B",
    "XComposer2-4KHD": "internlm/internlm-xcomposer2-4khd-7b",
    "LLaVA-NeXT-7B-Mistral": "llava-hf/llava-v1.6-mistral-7b-hf",
    "LLaVA-NeXT-7B-Vicuna": "llava-hf/llava-v1.6-vicuna-7b-hf",
    "LLaVA-NeXT-8B": "llava-hf/llama3-llava-next-8b-hf",
    "LLaVA-NeXT-13B": "llava-hf/llava-v1.6-vicuna-13b-hf",
    "LLaVA-NeXT-34B": "llava-hf/llava-v1.6-34b-hf",
    "InstructBLIP-Vicuna-7B": "Salesforce/instructblip-vicuna-7b",
    "LLaVA-NeXT-Interleave-7B": "llava-hf/llava-interleave-qwen-7b-hf",
    "Mantis-LLaMA3-SigLIP": "TIGER-Lab/Mantis-8B-siglip-llama3",
    "Mantis-Idefics2": "TIGER-Lab/Mantis-8B-Idefics2",
    "Idefics-2-8b": "HuggingFaceM4/idefics2-8b",
    "deepseek-vl2-tiny": "deepseek-ai/deepseek-vl2-tiny",
    "deepseek-vl2-small": "deepseek-ai/deepseek-vl2-small",
    "deepseek-vl2": "deepseek-ai/deepseek-vl2",
}